### ISSUE TITLE
Add a Better Readme file

### ISSUE THREAD

**Issue by Fr0stb1t3** [Fr0stb1t3/filetyperepo#4]
A more concise and fancy looking readme would be nice. Open for suggestions.

**Comment by KaneshiroKeola** [comment]
Please assign me this task I will Make the file into a short but nice-looking readme file.

**Comment by jude-san** [comment]
Please, can two or more work on the same issue?

**Comment by Fr0stb1t3** [comment]
Yeah, any number of people can work on this issue
I'm looking for a more comprehensive Readme which can bring people in for more contributions. Just mention this issue when creating a PR

**Comment by jude-san** [comment]
@Fr0stb1t3 Hi, any idea on how it should look like.

**Comment by Fr0stb1t3** [comment]
Hey @jude-san use this readme as a reference https://github.com/keon/algorithms/blob/master/README.md

**Comment by jude-san** [comment]
Thanks.

**Comment by jude-san** [comment]
done. created a pull request, please review.
